languageCode = "en-US"
defaultContentLanguage = "en-US"
[languages]
  [languages.en-US]
    languageName = "English"
    weight = 1
theme = "hugo-theme-reimu"
baseURL = "https://vnontop-de.github.io/"
publishDir = "."
[module]
  [module.hugoVersion]
    extended = true
    min = "0.116.0"
