name: Deploy Hugo Site
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: false  # Disable submodules to avoid unnecessary complexity
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.139.4"  # Adjust to your preferred Hugo version
          extended: true           # Enable if your theme requires the extended version
      - name: Build Site
        run: hugo --minify
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public    # Directory where Hugo builds your site
          publish_branch: gh-pages # Target branch for deployment
          force_orphan: true       # Ensures a clean gh-pages branch each time
