name: Deploy Hugo Site
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false  # Fix submodule error
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.139.4"
          extended: true
      - name: Build
        run: hugo --minify --theme hugo-theme-reimu  # Ensure theme is applied
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # Match config.toml publishDir
          publish_branch: main  # Deploy to main root
